version: '3.7'
services:

  db_one:
    image: postgres:13
    environment:
      - POSTGRES_USER=db_one_user
      - POSTGRES_PASSWORD=db_one_pass
      - POSTGRES_DB=db_one

  db_two:
    image: postgres:13
    environment:
      - POSTGRES_USER=db_two_user
      - POSTGRES_PASSWORD=db_two_pass
      - POSTGRES_DB=db_two

  nxodb:
    image: erlang:23
    volumes:
      - ".:/nxo_db"
    entrypoint:
      - /bin/bash
    tty: true
    stdin_open: true
    working_dir: /nxo_db
